version: '3.8'

services:
  app:
    build: .
    container_name: risa-medical-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - risa-network
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: risa-medical-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./public:/usr/share/nginx/html:ro
    networks:
      - risa-network

networks:
  risa-network:
    driver: bridge